version: '3.8'

services:
  postgres_for_download5sing:
    container_name: postgres_for_download5sing
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5438:5432"
    restart: always
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb:latest
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
volumes:
  postgres: